# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: ms2
services:
  mysql:
    extends:
      file: ./mysql.yml
      service: mysql
    profiles:
      - ''
      - prod
  keycloak:
    extends:
      file: ./keycloak.yml
      service: keycloak
  jhipster-registry:
    extends:
      file: ./jhipster-registry.yml
      service: jhipster-registry
    depends_on:
      keycloak:
        condition: service_healthy
  kafka:
    extends:
      file: ./kafka.yml
      service: kafka
